name: signal
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  devicelocale: ^0.6.0
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  go_router: ^9.0.3
  json_annotation: ^4.8.1
  logger: ^1.4.0
  package_info_plus: ^4.0.2
  shared_preferences: ^2.2.0
  sprintf: ^7.0.0
  version_tracker:
    git:
      url: https://github.com/holusojivhictor/version_tracker
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/gifs/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
